# Generated by Django 4.1 on 2024-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(max_length=50)),
                ("nachname", models.CharField(max_length=50)),
                ("strasse", models.CharField(max_length=50)),
                ("plz", models.CharField(max_length=5)),
                ("ort", models.CharField(max_length=50)),
                ("telefon", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
